# Generated by Django 4.1.6 on 2023-02-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='team',
            name='designation',
            field=models.CharField(max_length=250, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='team',
            name='fb_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на facebook'),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='team',
            name='te_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на telegram'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tw_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на twitter'),
        ),
        migrations.AlterField(
            model_name='team',
            name='wa_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на whatsapp'),
        ),
    ]
