# Generated by Django 4.1.6 on 2023-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_team_photo_alter_team_designation_alter_team_fb_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(default='img/avatar/withoutavatar.jpg', null=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
