# Generated by Django 4.1.6 on 2023-03-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_team_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(default='photo/withoutavatar.jpg', null=True, upload_to='photo/%Y/%m/%d'),
        ),
    ]
