# Generated by Django 4.1.6 on 2023-02-09 07:09

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('car_title', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('FRU', 'Bishkek'), ('CH', 'Chuy'), ('OSH', 'Osh'), ('NN', 'Naryn'), ('IK', 'Issyk Kul'), ('JA', 'Jalal Abad'), ('BN', 'Batken'), ('TS', 'Talas')], max_length=100)),
                ('city', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], verbose_name='year')),
                ('condition', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('car_main_photo', models.ImageField(blank=True, null=True, upload_to='photos/cars/%Y/%m/%d/')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('Parking Assist', 'Parking Assist'), ('Video Camera', 'Video Camera'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Wind Deflector', 'Wind Deflector'), ('Bluetooth Handset', 'Bluetooth Handset'), ('Auto Pilot', 'Auto Pilot'), ('ABS', 'ABS'), ('Luke', 'Luke')], max_length=255)),
                ('body_style', models.CharField(max_length=255)),
                ('engine', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('interior', models.CharField(max_length=255)),
                ('kilometers', models.IntegerField()),
                ('doors', models.CharField(max_length=255)),
                ('passengers', models.IntegerField()),
                ('vin_no', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(max_length=255)),
                ('no_of_owners', models.IntegerField()),
                ('fuel_mileage', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(upload_to='photos/cars/car_photos/%Y/%m/%d/')),
                ('car_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'verbose_name': 'Car photo',
                'verbose_name_plural': 'Car photos',
            },
        ),
    ]
