# Generated by Django 4.1.6 on 2023-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='image',
            field=models.FileField(null=True, upload_to='photos/cars/car_photos/%Y/%m/%d/'),
        ),
    ]
