# Generated by Django 4.1.6 on 2023-02-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
